from .entity_by_id_query import IEntityByIdQuery
from .film_by_id_query import IFilmByIdQuery
from .genre_by_id_query import IGenreByIdQuery
from .sorted_films_query import IFilmsQuery
from .search_films_query import ISearchFilmsQuery
from .genres_query import IGenresQuery
from .person_by_id_query import IPersonByIdQuery
from .search_persons_query import ISearchPersonsQuery
from .films_person_by_id_query import IFilmsPersonByIdQuery
from .persons_query import IPersonsQuery
