from .film_by_id_query import FilmByIdQuery
from .genre_by_id_query import GenreByIdQuery
from .sort_films_query import FilmsQuery
from .search_films_query import SearchFilmsQuery
from .search_persons_query import SearchPersonsQuery
from .genres_query import GenresQuery
from .person_by_id_query import PersonByIdQuery
from .films_person_by_id_query import FilmsPersonByIdQuery
from .persons_query import PersonsQuery
